import { MigrationInterface, QueryRunner } from 'typeorm';

export class InitialSchema1789190733244 implements MigrationInterface {
  name = 'InitialSchema1789190733244';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE "ingredient_categories" ("category_id" smallint GENERATED BY DEFAULT AS IDENTITY NOT NULL, "name" character varying(50) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "uq_ingredient_categories_name" UNIQUE ("name"), CONSTRAINT "PK_568d581d7aa0253e7eb4c84c3ea" PRIMARY KEY ("category_id"))`,
    );
    await queryRunner.query(
      `CREATE TABLE "ingredient_unit_conversions" ("ingredient_id" bigint NOT NULL, "from_unit_id" smallint NOT NULL, "to_unit_id" smallint NOT NULL, "conversion_factor" numeric(18,9) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "chk_ingredient_conversion_different_units" CHECK ("from_unit_id" <> "to_unit_id"), CONSTRAINT "chk_ingredient_conversion_factor" CHECK ("conversion_factor" > 0), CONSTRAINT "PK_214a13969cb6e7d0fc1ff62396e" PRIMARY KEY ("ingredient_id", "from_unit_id", "to_unit_id"))`,
    );
    await queryRunner.query(
      `CREATE TABLE "units" ("unit_id" smallint GENERATED BY DEFAULT AS IDENTITY NOT NULL, "name" character varying(30) NOT NULL, "abbreviation" character varying(10) NOT NULL, "unit_type" character varying(20) NOT NULL, "conversion_to_base" numeric(18,9) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "uq_units_abbreviation" UNIQUE ("abbreviation"), CONSTRAINT "uq_units_name" UNIQUE ("name"), CONSTRAINT "chk_units_conversion_positive" CHECK ("conversion_to_base" > 0), CONSTRAINT "chk_units_type" CHECK ("unit_type" IN ('weight', 'volume', 'count')), CONSTRAINT "PK_5cef2f225de998fb92c007f0cae" PRIMARY KEY ("unit_id"))`,
    );
    await queryRunner.query(
      `CREATE TABLE "retailers" ("retailer_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL, "name" character varying(100) NOT NULL, "website_url" character varying(500), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "uq_retailers_name" UNIQUE ("name"), CONSTRAINT "PK_ab7d8c80579ca444f248b16a70c" PRIMARY KEY ("retailer_id"))`,
    );
    await queryRunner.query(
      `CREATE TABLE "store_locations" ("store_location_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL, "retailer_id" bigint NOT NULL, "store_number" character varying(50), "address_line1" character varying(150) NOT NULL, "address_line2" character varying(150), "city" character varying(100) NOT NULL, "state_code" character varying(10) NOT NULL, "postal_code" character varying(20) NOT NULL, "country_code" character(2) NOT NULL DEFAULT 'US', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "uq_store_location_number" UNIQUE ("retailer_id", "store_number"), CONSTRAINT "PK_54424c334926600c41a9768b19e" PRIMARY KEY ("store_location_id"))`,
    );
    await queryRunner.query(
      `CREATE INDEX "idx_store_locations_postal_code" ON "store_locations"  ("postal_code") `,
    );
    await queryRunner.query(
      `CREATE INDEX "idx_store_locations_retailer_id" ON "store_locations"  ("retailer_id") `,
    );
    await queryRunner.query(
      `CREATE TABLE "product_prices" ("price_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL, "product_id" bigint NOT NULL, "store_location_id" bigint NOT NULL, "price" numeric(12,2) NOT NULL, "currency_code" character(3) NOT NULL DEFAULT 'USD', "recorded_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "uq_product_price_observation" UNIQUE ("product_id", "store_location_id", "recorded_at"), CONSTRAINT "chk_product_price_nonnegative" CHECK ("price" >= 0), CONSTRAINT "PK_41790eaf6a1a1efa67ddeb03802" PRIMARY KEY ("price_id"))`,
    );
    await queryRunner.query(
      `CREATE INDEX "idx_product_prices_store_location_id" ON "product_prices"  ("store_location_id") `,
    );
    await queryRunner.query(
      `CREATE INDEX "idx_product_prices_product_id" ON "product_prices"  ("product_id") `,
    );
    await queryRunner.query(
      `CREATE TABLE "users" ("user_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL, "email" character varying(254) NOT NULL, "password_hash" text NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "uq_users_email" UNIQUE ("email"), CONSTRAINT "PK_96aac72f1574b88752e9fb00089" PRIMARY KEY ("user_id"))`,
    );
    await queryRunner.query(
      `CREATE TABLE "ingredient_products" ("product_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL, "ingredient_id" bigint NOT NULL, "package_unit_id" smallint NOT NULL, "brand" character varying(100), "product_name" character varying(150) NOT NULL, "package_quantity" numeric(12,4) NOT NULL, "upc" character varying(20), "user_id" bigint NOT NULL, "version" integer NOT NULL DEFAULT '1', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "uq_product_user_upc" UNIQUE ("user_id", "upc"), CONSTRAINT "chk_product_package_quantity" CHECK ("package_quantity" > 0), CONSTRAINT "PK_0c3d5f636fbc33d8dd26e699bee" PRIMARY KEY ("product_id"))`,
    );
    await queryRunner.query(
      `CREATE INDEX "idx_ingredient_products_package_unit_id" ON "ingredient_products"  ("package_unit_id") `,
    );
    await queryRunner.query(
      `CREATE INDEX "idx_ingredient_products_ingredient_id" ON "ingredient_products"  ("ingredient_id") `,
    );
    await queryRunner.query(
      `CREATE INDEX "idx_ingredient_products_user_id" ON "ingredient_products"  ("user_id") `,
    );
    await queryRunner.query(
      `CREATE TABLE "ingredients" ("ingredient_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL, "category_id" smallint, "name" character varying(100) NOT NULL, "description" text, "user_id" bigint, "version" integer NOT NULL DEFAULT '1', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_ca1733bfdc5be587ed299844ac1" PRIMARY KEY ("ingredient_id"))`,
    );
    await queryRunner.query(
      `CREATE INDEX "idx_ingredients_category_id" ON "ingredients"  ("category_id") `,
    );
    await queryRunner.query(
      `CREATE UNIQUE INDEX "uq_ingredients_private_name" ON "ingredients"  ("user_id", "name") WHERE "user_id" IS NOT NULL`,
    );
    await queryRunner.query(
      `CREATE UNIQUE INDEX "uq_ingredients_shared_name" ON "ingredients"  ("name") WHERE "user_id" IS NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE "ingredient_unit_conversions" ADD CONSTRAINT "FK_044876911afe4e6a0a438047dc9" FOREIGN KEY ("ingredient_id") REFERENCES "ingredients"("ingredient_id") ON DELETE CASCADE ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "ingredient_unit_conversions" ADD CONSTRAINT "FK_ba8e4772bb4f6ee3e5abe5fbff4" FOREIGN KEY ("from_unit_id") REFERENCES "units"("unit_id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "ingredient_unit_conversions" ADD CONSTRAINT "FK_3e7970b037996c6c625d47fcef0" FOREIGN KEY ("to_unit_id") REFERENCES "units"("unit_id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "store_locations" ADD CONSTRAINT "FK_f9b5683788dc2ebc7e977176d9c" FOREIGN KEY ("retailer_id") REFERENCES "retailers"("retailer_id") ON DELETE RESTRICT ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "product_prices" ADD CONSTRAINT "FK_8218c69c7f5a3706662101fa788" FOREIGN KEY ("product_id") REFERENCES "ingredient_products"("product_id") ON DELETE CASCADE ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "product_prices" ADD CONSTRAINT "FK_0f79b18794daf783aed8880e0c4" FOREIGN KEY ("store_location_id") REFERENCES "store_locations"("store_location_id") ON DELETE CASCADE ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "ingredient_products" ADD CONSTRAINT "FK_e2909bbd744fc6f086d62c53ec2" FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE RESTRICT ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "ingredient_products" ADD CONSTRAINT "FK_5889f71b45987908fffb6fb6b53" FOREIGN KEY ("ingredient_id") REFERENCES "ingredients"("ingredient_id") ON DELETE RESTRICT ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "ingredient_products" ADD CONSTRAINT "FK_cb756653d6b6fba1db73b80f2d1" FOREIGN KEY ("package_unit_id") REFERENCES "units"("unit_id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "ingredients" ADD CONSTRAINT "FK_317acbdff49aeb8558a1bc6c606" FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE RESTRICT ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "ingredients" ADD CONSTRAINT "FK_78cffcca39dfbf7958936c750f6" FOREIGN KEY ("category_id") REFERENCES "ingredient_categories"("category_id") ON DELETE SET NULL ON UPDATE NO ACTION`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE "ingredients" DROP CONSTRAINT "FK_78cffcca39dfbf7958936c750f6"`,
    );
    await queryRunner.query(
      `ALTER TABLE "ingredients" DROP CONSTRAINT "FK_317acbdff49aeb8558a1bc6c606"`,
    );
    await queryRunner.query(
      `ALTER TABLE "ingredient_products" DROP CONSTRAINT "FK_cb756653d6b6fba1db73b80f2d1"`,
    );
    await queryRunner.query(
      `ALTER TABLE "ingredient_products" DROP CONSTRAINT "FK_5889f71b45987908fffb6fb6b53"`,
    );
    await queryRunner.query(
      `ALTER TABLE "ingredient_products" DROP CONSTRAINT "FK_e2909bbd744fc6f086d62c53ec2"`,
    );
    await queryRunner.query(
      `ALTER TABLE "product_prices" DROP CONSTRAINT "FK_0f79b18794daf783aed8880e0c4"`,
    );
    await queryRunner.query(
      `ALTER TABLE "product_prices" DROP CONSTRAINT "FK_8218c69c7f5a3706662101fa788"`,
    );
    await queryRunner.query(
      `ALTER TABLE "store_locations" DROP CONSTRAINT "FK_f9b5683788dc2ebc7e977176d9c"`,
    );
    await queryRunner.query(
      `ALTER TABLE "ingredient_unit_conversions" DROP CONSTRAINT "FK_3e7970b037996c6c625d47fcef0"`,
    );
    await queryRunner.query(
      `ALTER TABLE "ingredient_unit_conversions" DROP CONSTRAINT "FK_ba8e4772bb4f6ee3e5abe5fbff4"`,
    );
    await queryRunner.query(
      `ALTER TABLE "ingredient_unit_conversions" DROP CONSTRAINT "FK_044876911afe4e6a0a438047dc9"`,
    );
    await queryRunner.query(`DROP INDEX "public"."uq_ingredients_shared_name"`);
    await queryRunner.query(
      `DROP INDEX "public"."uq_ingredients_private_name"`,
    );
    await queryRunner.query(
      `DROP INDEX "public"."idx_ingredients_category_id"`,
    );
    await queryRunner.query(`DROP TABLE "ingredients"`);
    await queryRunner.query(
      `DROP INDEX "public"."idx_ingredient_products_user_id"`,
    );
    await queryRunner.query(
      `DROP INDEX "public"."idx_ingredient_products_ingredient_id"`,
    );
    await queryRunner.query(
      `DROP INDEX "public"."idx_ingredient_products_package_unit_id"`,
    );
    await queryRunner.query(`DROP TABLE "ingredient_products"`);
    await queryRunner.query(`DROP TABLE "users"`);
    await queryRunner.query(
      `DROP INDEX "public"."idx_product_prices_product_id"`,
    );
    await queryRunner.query(
      `DROP INDEX "public"."idx_product_prices_store_location_id"`,
    );
    await queryRunner.query(`DROP TABLE "product_prices"`);
    await queryRunner.query(
      `DROP INDEX "public"."idx_store_locations_retailer_id"`,
    );
    await queryRunner.query(
      `DROP INDEX "public"."idx_store_locations_postal_code"`,
    );
    await queryRunner.query(`DROP TABLE "store_locations"`);
    await queryRunner.query(`DROP TABLE "retailers"`);
    await queryRunner.query(`DROP TABLE "units"`);
    await queryRunner.query(`DROP TABLE "ingredient_unit_conversions"`);
    await queryRunner.query(`DROP TABLE "ingredient_categories"`);
  }
}
