import { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateUsers1789097362058 implements MigrationInterface {
  name = 'CreateUsers1789097362058';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE "ingredient_unit_conversions" DROP CONSTRAINT "ingredient_unit_conversions_from_unit_id_fkey"`,
    );
    await queryRunner.query(
      `ALTER TABLE "ingredient_unit_conversions" DROP CONSTRAINT "ingredient_unit_conversions_ingredient_id_fkey"`,
    );
    await queryRunner.query(
      `ALTER TABLE "ingredient_unit_conversions" DROP CONSTRAINT "ingredient_unit_conversions_to_unit_id_fkey"`,
    );
    await queryRunner.query(
      `ALTER TABLE "store_locations" DROP CONSTRAINT "store_locations_retailer_id_fkey"`,
    );
    await queryRunner.query(
      `ALTER TABLE "product_prices" DROP CONSTRAINT "product_prices_product_id_fkey"`,
    );
    await queryRunner.query(
      `ALTER TABLE "product_prices" DROP CONSTRAINT "product_prices_store_location_id_fkey"`,
    );
    await queryRunner.query(
      `ALTER TABLE "ingredient_products" DROP CONSTRAINT "ingredient_products_ingredient_id_fkey"`,
    );
    await queryRunner.query(
      `ALTER TABLE "ingredient_products" DROP CONSTRAINT "ingredient_products_package_unit_id_fkey"`,
    );
    await queryRunner.query(
      `ALTER TABLE "ingredients" DROP CONSTRAINT "ingredients_category_id_fkey"`,
    );
    await queryRunner.query(
      `DROP INDEX "public"."idx_product_prices_product_store_recorded"`,
    );
    await queryRunner.query(
      `CREATE TABLE "users" ("user_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL, "email" character varying(254) NOT NULL, "password_hash" text NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "uq_users_email" UNIQUE ("email"), CONSTRAINT "PK_96aac72f1574b88752e9fb00089" PRIMARY KEY ("user_id"))`,
    );
    await queryRunner.query(
      `ALTER TABLE "ingredient_unit_conversions" ADD CONSTRAINT "FK_044876911afe4e6a0a438047dc9" FOREIGN KEY ("ingredient_id") REFERENCES "ingredients"("ingredient_id") ON DELETE CASCADE ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "ingredient_unit_conversions" ADD CONSTRAINT "FK_ba8e4772bb4f6ee3e5abe5fbff4" FOREIGN KEY ("from_unit_id") REFERENCES "units"("unit_id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "ingredient_unit_conversions" ADD CONSTRAINT "FK_3e7970b037996c6c625d47fcef0" FOREIGN KEY ("to_unit_id") REFERENCES "units"("unit_id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "store_locations" ADD CONSTRAINT "FK_f9b5683788dc2ebc7e977176d9c" FOREIGN KEY ("retailer_id") REFERENCES "retailers"("retailer_id") ON DELETE RESTRICT ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "product_prices" ADD CONSTRAINT "FK_8218c69c7f5a3706662101fa788" FOREIGN KEY ("product_id") REFERENCES "ingredient_products"("product_id") ON DELETE CASCADE ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "product_prices" ADD CONSTRAINT "FK_0f79b18794daf783aed8880e0c4" FOREIGN KEY ("store_location_id") REFERENCES "store_locations"("store_location_id") ON DELETE CASCADE ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "ingredient_products" ADD CONSTRAINT "FK_5889f71b45987908fffb6fb6b53" FOREIGN KEY ("ingredient_id") REFERENCES "ingredients"("ingredient_id") ON DELETE RESTRICT ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "ingredient_products" ADD CONSTRAINT "FK_cb756653d6b6fba1db73b80f2d1" FOREIGN KEY ("package_unit_id") REFERENCES "units"("unit_id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "ingredients" ADD CONSTRAINT "FK_78cffcca39dfbf7958936c750f6" FOREIGN KEY ("category_id") REFERENCES "ingredient_categories"("category_id") ON DELETE SET NULL ON UPDATE NO ACTION`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE "ingredients" DROP CONSTRAINT "FK_78cffcca39dfbf7958936c750f6"`,
    );
    await queryRunner.query(
      `ALTER TABLE "ingredient_products" DROP CONSTRAINT "FK_cb756653d6b6fba1db73b80f2d1"`,
    );
    await queryRunner.query(
      `ALTER TABLE "ingredient_products" DROP CONSTRAINT "FK_5889f71b45987908fffb6fb6b53"`,
    );
    await queryRunner.query(
      `ALTER TABLE "product_prices" DROP CONSTRAINT "FK_0f79b18794daf783aed8880e0c4"`,
    );
    await queryRunner.query(
      `ALTER TABLE "product_prices" DROP CONSTRAINT "FK_8218c69c7f5a3706662101fa788"`,
    );
    await queryRunner.query(
      `ALTER TABLE "store_locations" DROP CONSTRAINT "FK_f9b5683788dc2ebc7e977176d9c"`,
    );
    await queryRunner.query(
      `ALTER TABLE "ingredient_unit_conversions" DROP CONSTRAINT "FK_3e7970b037996c6c625d47fcef0"`,
    );
    await queryRunner.query(
      `ALTER TABLE "ingredient_unit_conversions" DROP CONSTRAINT "FK_ba8e4772bb4f6ee3e5abe5fbff4"`,
    );
    await queryRunner.query(
      `ALTER TABLE "ingredient_unit_conversions" DROP CONSTRAINT "FK_044876911afe4e6a0a438047dc9"`,
    );
    await queryRunner.query(`DROP TABLE "users"`);
    await queryRunner.query(
      `CREATE INDEX "idx_product_prices_product_store_recorded" ON "product_prices" USING btree ("product_id", "recorded_at", "store_location_id") `,
    );
    await queryRunner.query(
      `ALTER TABLE "ingredients" ADD CONSTRAINT "ingredients_category_id_fkey" FOREIGN KEY ("category_id") REFERENCES "ingredient_categories"("category_id") ON DELETE SET NULL ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "ingredient_products" ADD CONSTRAINT "ingredient_products_package_unit_id_fkey" FOREIGN KEY ("package_unit_id") REFERENCES "units"("unit_id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "ingredient_products" ADD CONSTRAINT "ingredient_products_ingredient_id_fkey" FOREIGN KEY ("ingredient_id") REFERENCES "ingredients"("ingredient_id") ON DELETE RESTRICT ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "product_prices" ADD CONSTRAINT "product_prices_store_location_id_fkey" FOREIGN KEY ("store_location_id") REFERENCES "store_locations"("store_location_id") ON DELETE CASCADE ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "product_prices" ADD CONSTRAINT "product_prices_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "ingredient_products"("product_id") ON DELETE CASCADE ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "store_locations" ADD CONSTRAINT "store_locations_retailer_id_fkey" FOREIGN KEY ("retailer_id") REFERENCES "retailers"("retailer_id") ON DELETE RESTRICT ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "ingredient_unit_conversions" ADD CONSTRAINT "ingredient_unit_conversions_to_unit_id_fkey" FOREIGN KEY ("to_unit_id") REFERENCES "units"("unit_id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "ingredient_unit_conversions" ADD CONSTRAINT "ingredient_unit_conversions_ingredient_id_fkey" FOREIGN KEY ("ingredient_id") REFERENCES "ingredients"("ingredient_id") ON DELETE CASCADE ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "ingredient_unit_conversions" ADD CONSTRAINT "ingredient_unit_conversions_from_unit_id_fkey" FOREIGN KEY ("from_unit_id") REFERENCES "units"("unit_id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
  }
}
